version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - prodnetwork
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - prodnetwork
  demo:
    image: anywhereinfo/demo
    ports:
      - "8080:8080"
    links:
      - kafka:kafka
      - zookeeper:zookeeper
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    container_name: spring-kafka-demo
    networks:
      - prodnetwork

      
      